### ISSUE TITLE
installation failed on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by fpiccinali** [modoboa/modoboa-installer#1]
i am trying to install modoboa on a fresh ubuntu and it fail with this message : 
```
 No such file or directory: '/srv/modoboa/instance/media/webmail'
```

Here is my session : 
```
cd /root
git clone https://github.com/modoboa/modoboa-installer
cd modoboa-installer
./run.py myserver

Welcome to Modoboa installer!
Your mail server myserver will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) 
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Installing modoboa
Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 113, in post_run
    self.apply_settings()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 92, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 82, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'
```

Another trick, if i edit installer.cfg with "engine=mysql", i have this error : 
```
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 136, in run
    self.setup_database()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 53, in setup_database
    self.backend = database.get_backend(self.config)
  File "/root/modoboa-installer/modoboa_installer/database.py", line 167, in get_backend
    return backend(config)
  File "/root/modoboa-installer/modoboa_installer/database.py", line 25, in __init__
    self.install_package()
  File "/root/modoboa-installer/modoboa_installer/database.py", line 119, in install_package
    super(MySQL, self).install_package()
  File "/root/modoboa-installer/modoboa_installer/database.py", line 29, in install_package
    utils.install_system_packages(self.packages)
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 76, in install_system_packages
    exec_cmd("apt-get install --quiet --assume-yes {}".format(" ".join(names)))
TypeError
```
In tried to print names, and it seems empty !

**Comment by tonioo** [comment]
Hi, the mysql issue should be fixed with this commit.

About the mkdir issue, can you list the content of /srv/modoboa please ?

**Comment by fpiccinali** [comment]
hello tonioo, 
i confirm that mysql is fixed.

But i still have error: 
```
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 82, in mkdir                                                                                                    
    os.mkdir(path, mode)                                                                                                                                                          
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'  
```
Here is the ls of /srv :
![screen2](https://cloud.githubusercontent.com/assets/9351145/10671074/f255c63a-78e8-11e5-8eaa-673dce76dab7.png)

![screen2](https://cloud.githubusercontent.com/assets/9351145/10671050/d256d482-78e8-11e5-8315-6be53369a925.png)

**Comment by fpiccinali** [comment]
@tonioo : how can i contribute to this project. I have added some small comments in installer.cfg and i would like to submit a pull request. 
 
i made a local branch, commit my changes and when i want to push ...
```
git push
Username for 'https://github.com': fpiccinali
Password for 'https://fpiccinali@github.com': 
remote: Permission to modoboa/modoboa-installer.git denied to fpiccinali.
fatal: unable to access 'https://github.com/modoboa/modoboa-installer/': The requested URL returned error: 403
```

**Comment by tonioo** [comment]
Can you try to run the installer using the --debug option please? It looks like the deployment step fails for some reason...

To contribute, you can't push directly to this repository since you're not a team member. You need to do it the Github way:
* Fork this repository (click on the button)
* Commit your changes on your copy
* Make a "pull request"

**Comment by fpiccinali** [comment]
```
cd /srv
rm -rf modoboa*
cd /root/modoboa-installer
./run.py --debug myserver
Welcome to Modoboa installer!
Your mail server myserver will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) 
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Réception de : 1 http://security.ubuntu.com trusty-security InRelease [64,4 kB]
... etc ...
Réception de : 30 http://fr.archive.ubuntu.com trusty-updates/universe Translation-en [170 kB]
Atteint http://fr.archive.ubuntu.com trusty Release
... etc ..
Atteint http://fr.archive.ubuntu.com trusty/main Sources
... etc ...
Atteint http://fr.archive.ubuntu.com trusty/universe Translation-en
Ign http://fr.archive.ubuntu.com trusty/main Translation-fr_FR
Ign http://fr.archive.ubuntu.com trusty/multiverse Translation-fr_FR
Ign http://fr.archive.ubuntu.com trusty/restricted Translation-fr_FR
Ign http://fr.archive.ubuntu.com trusty/universe Translation-fr_FR
4 053 ko réceptionnés en 11s (355 ko/s)
Lecture des listes de paquets…
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
sudo is already the newest version.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
Installing modoboa
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
libjpeg-dev is already the newest version.
librrd-dev is already the newest version.
libxslt1-dev is already the newest version.
python-dev is already the newest version.
rrdtool is already the newest version.
libxml2-dev is already the newest version.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
postgresql is already the newest version.
postgresql-server-dev-all is already the newest version.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
 * Starting PostgreSQL 9.3 database server                                                                                            [ OK ] 
could not change directory to "/root/modoboa-installer": Permission denied
could not change directory to "/root/modoboa-installer": Permission denied
1
could not change directory to "/root/modoboa-installer": Permission denied
createdb: database creation failed: ERROR:  database "modoboa" already exists
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
python-virtualenv is already the newest version.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 3, in <module>
    virtualenv.main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 985, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1159, in install_python
    mkdir(lib_dir)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 447, in mkdir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/srv/modoboa'
sudo: /srv/modoboa/env/bin/pip: command not found
sudo: /srv/modoboa/env/bin/pip: command not found
Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 112, in post_run
    self._deploy_instance()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 73, in _deploy_instance
    sudo_user=self.user, cwd=self.home_dir)
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 58, in exec_cmd
    process = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/srv/modoboa'
```

**Comment by fpiccinali** [comment]
about : 
```
could not change directory to "/root/modoboa-installer": Permission denied
```
i tried with modoboa_installer in a public folder (/tmp) and the message disapear.
It remains the other errors

**Comment by tonioo** [comment]
The installer needs root privileges to run. How did you run the installer ? Using sudo or as root ?

**Comment by fpiccinali** [comment]
as root

**Comment by fpiccinali** [comment]
si tu veux je suis dispo pour faire une séquence de test à deux par skype ou au tél.
ça risque d'être pénible a trouver ce genre de problème de droits.

**Comment by tonioo** [comment]
Sure, skype would be fine. Do you know my private email ?

**Comment by tonioo** [comment]
Can I close this issue ?

**Comment by ucwinds** [comment]
I have the same issue with " No such file or directory: '/srv/modoboa/instance/media/webmail'" on a clean Debian and run as root. Can you share the fix? Thank you.

**Comment by fpiccinali** [comment]
no there is some new issues. 

I have made test from scratch with an ubuntu-server 14.04 LTS
The first one with the default parameter -i.e postgres - and the second with mysql.

With postgres it seems ok, i can connect to modoboa. 
With mysql, when i try a login i am redirected to https://myserver/admin/domains/ witch displays: 
```
Sorry
An internal error occured.
```

I do not know where are logs file in order to help analyze. 

During the process of installation i notice those errors|warnings : 
```
Successfully installed LEPL-5.1.3 chardet-2.3.0 future-0.15.2 lxml-3.4.4 modoboa-admin-1.1.2 modoboa-admin-limits-1.0.2 modoboa-admin-relaydomains-1.1.0 modoboa-amavis-1.0.3 modoboa-pdfcredentials-1.0.0 modoboa-postfix-autoreply-1.1.1 modoboa-sievefilters-1.0.3 modoboa-stats-1.0.2 modoboa-webmail-1.0.2 pillow-3.0.0 progressbar-2.3 pytz-2015.6 reportlab-3.2.0 rfc6266-0.0.4 sievelib-0.9.2
ERROR 1045 (28000): Access denied for user 'modoboa'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'modoboa'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'modoboa'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'modoboa'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'modoboa'@'localhost' (using password: YES)

Starting amavisd:   The value of variable $myhostname is "srv138", but should have been
  a fully qualified domain name; perhaps uname(3) did not provide such.
  You must explicitly assign a FQDN of this host to variable $myhostname
  in /etc/amavis/conf.d/05-node_id, or fix what uname(3) provides as a host's 
  network name!
(failed).
invoke-rc.d: initscript amavis, action "start" failed.
WARNING: Starting amavisd-new failed. Please check your configuration.

ERROR 1005 (HY000) at line 179: Can't create table 'amavis.msgrcpt' (errno: 150)

SpamAssassin Mail Filter Daemon: disabled, see /etc/default/spamassassin

Paramétrage de clamav-daemon (0.98.7+dfsg-0ubuntu0.14.04.1) ...
 * Clamav signatures not found in /var/lib/clamav
 * Please retrieve them using freshclam
 * Then run '/etc/init.d/clamav-daemon start'

Processing triggers for ureadahead (0.100.0-16) ...
 * clamd is not running
 * Clamav signatures not found in /var/lib/clamav
 * Please retrieve them using freshclam
 * Then run '/etc/init.d/clamav-daemon start'
 * amavisd is not running

```

I can connect to msql, databases are created, and in amavis i have theses tables : 
````
+------------------+
| Tables_in_amavis |
+------------------+
| maddr            |
| mailaddr         |
| msgs             |
| policy           |
| users            |
| wblist           |
+------------------+
````

About clamav, i am going to write a tuto in README.rst

**Comment by tonioo** [comment]
Indeed, there is a permission issue with MySQL... Maybe the way I create users and assign privileges is wrong. I'll try to reproduce it asap.
About freshclam, what do you want to do ? Because I already download cvd files during the process.

**Comment by fpiccinali** [comment]
freshclam
/etc/init.d/clamav-daemon restart

**Comment by tonioo** [comment]
The permission issue should be fixed now. I already run freshclam.
https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/clamav.py#L23

**Comment by fpiccinali** [comment]
Did you push your changes ?
Error are still there : 
```
service clamav-daemon restart
 * Stopping ClamAV daemon clamd                                                                                                                                             [ OK ] 
 * Clamav signatures not found in /var/lib/clamav
 * Please retrieve them using freshclam
 * Then run '/etc/init.d/clamav-daemon start'
```

On login, i have this error : 
```
  Sorry An internal error occured.
```

During the installation, i see these errors : 
In postfixinstall: 
```
 Adding mysql map entry to /etc/postfix/dynamicmaps.cf
 Unknown extension modoboa_radicale
 Unknown extension modoboa_imap_migration 
 * postfix is running
```

In amavis install : 
```
 ERROR 1005 (HY000) at line 179: Can't create table 'amavis.msgrcpt' (errno: 150)
```

i am skypable today if you need.

**Comment by tonioo** [comment]
I don't understand the clamav issue, the code has not changed recently and I can't reproduce this issue...

For the internal error, try to set DEBUG to True inside settings.py, you should see a complete stack trace.

I've fixed the postfix issue with my previous commit.

The amavis error is "normal" because the installer tries to create tables which already exist. This is a just a warning...

**Comment by fpiccinali** [comment]
ça marche !

J'ai essayé DEBUG = True dans settings.py mais je n'ai pas eu de stacktrace.

J'ai refait une installation from scratch et j'ai juste changé "engine = mysql" dans installer.cfg
---> succès

Ensuite, je réinstalle un OS, et je recommence la manip mais en configurant les mots de passe mysql par autre chose dans installer.cfg.
--> succès

PS: saurais tu me recommander un outil pour voir les tables MYSQL. Habituellement j'utilise phpmyadmin, mais dans cette configuration j'aimerai me passer de la totale APACHE/PHP. Est ce qu'en python il y a un équivalent ? 

You can close this issue.

**Comment by tonioo** [comment]
Unfortunately, I don't know such a tool. I generally only use the command line tool...

**Comment by mawesome4ever** [comment]
I'm running into this exact same issue installing on Ubuntu 24.04. Here is the debug info when installing. Btw, this is on a fresh Ubuntu server.
`Welcome to Modoboa installer!

Checking the installer...
Installer seems up to date!
Checks complete

Notice:
It is recommanded to run this installer on a FRESHLY installed server.
(ie. with nothing special already installed on it)

Warning:
Before you start the installation, please make sure the following DNS records exist for domain 'eggsdstudios.com':
  mail IN A   <IP ADDRESS OF YOUR SERVER>
     @ IN MX  mail.eggsdstudios.com.

Your mail server will be installed with the following components:
fail2ban modoboa automx amavis clamav dovecot nginx razor postfix postwhite spamassassin uwsgi radicale opendkim
Do you confirm? (Y/n) 
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Hit:1 http://mirrors.digitalocean.com/ubuntu noble InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu noble-updates InRelease
Hit:3 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:4 http://mirrors.digitalocean.com/ubuntu noble-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu noble-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
sudo is already the newest version (1.9.15p5-3ubuntu5).
wget is already the newest version (1.21.4-1ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Generating new certificate using letsencrypt
Reading package lists...
Building dependency tree...
Reading state information...
software-properties-common is already the newest version (0.99.48).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://mirrors.digitalocean.com/ubuntu noble InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu noble-updates InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu noble-backports InRelease
Hit:4 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:5 http://security.ubuntu.com/ubuntu noble-security InRelease
Reading package lists...
Adding component(s) 'universe' to all repositories.
Reading package lists...
Building dependency tree...
Reading state information...
certbot is already the newest version (2.9.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-certbot-nginx is already the newest version (2.9.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Certificate not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Installing amavis
Reading package lists...
Building dependency tree...
Reading state information...
mariadb-server is already the newest version (1:10.11.7-2ubuntu2).
libmariadb-dev is already the newest version (1:10.11.7-2ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Synchronizing state of mariadb.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable mariadb
● mariadb.service - MariaDB 10.11.7 database server
     Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-05-19 05:15:56 UTC; 2min 20s ago
       Docs: man:mariadbd(8)
             https://mariadb.com/kb/en/library/systemd/
   Main PID: 60491 (mariadbd)
     Status: "Taking your SQL requests now..."
      Tasks: 11 (limit: 30745)
     Memory: 79.1M (peak: 82.1M)
        CPU: 772ms
     CGroup: /system.slice/mariadb.service
             └─60491 /usr/sbin/mariadbd

May 19 05:15:56 mail.eggsdstudios.com mariadbd[60491]: Version: '10.11.7-MariaDB-2ubuntu2'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Ubuntu 24.04
May 19 05:15:56 mail.eggsdstudios.com systemd[1]: Started mariadb.service - MariaDB 10.11.7 database server.
May 19 05:15:56 mail.eggsdstudios.com /etc/mysql/debian-start[60507]: Upgrading MariaDB tables if necessary.
May 19 05:15:57 mail.eggsdstudios.com /etc/mysql/debian-start[60531]: Triggering myisam-recover for all MyISAM tables and aria-recover for all Aria tables
May 19 05:15:58 mail.eggsdstudios.com mariadbd[60491]: 2024-05-19  5:15:58 34 [Warning] Access denied for user 'root'@'localhost'
May 19 05:15:58 mail.eggsdstudios.com mariadbd[60491]: 2024-05-19  5:15:58 35 [Warning] Access denied for user 'root'@'localhost'
May 19 05:15:58 mail.eggsdstudios.com mariadbd[60491]: 2024-05-19  5:15:58 36 [Warning] Access denied for user 'root'@'localhost'
May 19 05:15:58 mail.eggsdstudios.com mariadbd[60491]: 2024-05-19  5:15:58 37 [Warning] Access denied for user 'root'@'localhost'
May 19 05:15:58 mail.eggsdstudios.com mariadbd[60491]: 2024-05-19  5:15:58 38 [Warning] Access denied for user 'root'@'localhost'
May 19 05:15:58 mail.eggsdstudios.com mariadbd[60491]: 2024-05-19  5:15:58 39 [Warning] Access denied for user 'amavis'@'localhost'
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Reading package lists...
Building dependency tree...
Reading state information...
libdbi-perl is already the newest version (1.643-4build3).
amavisd-new is already the newest version (1:2.13.0-3ubuntu1).
arc is already the newest version (5.21q-12).
arj is already the newest version (3.10.22-27).
cabextract is already the newest version (1.11-2).
liblz4-tool is already the newest version (1.9.4-1build1).
lrzip is already the newest version (0.651-2ubuntu1).
lzop is already the newest version (1.04-2build3).
p7zip-full is already the newest version (16.02+transitional.1).
rpm2cpio is already the newest version (4.18.2+dfsg-2.1build2).
unrar-free is already the newest version (1:0.1.3-1build2).
libdbd-mysql-perl is already the newest version (4.052-1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
Version: 1:2.13.0-3ubuntu1
ERROR 1698 (28000): Access denied for user 'amavis'@'localhost'
Installing spamassassin
Reading package lists...
^CTraceback (most recent call last):
  File "/root/modoboa-installer/./run.py", line 317, in <module>
    main(sys.argv[1:])
  File "/root/modoboa-installer/./run.py", line 288, in main
    scripts.install(appname, config, args.upgrade, args.restore)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 29, in install
    getattr(script, appname.capitalize())(config, upgrade, archive_path).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 206, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/amavis.py", line 95, in post_run
    install("spamassassin", self.config, self.upgrade, self.archive_path)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 29, in install
    getattr(script, appname.capitalize())(config, upgrade, archive_path).run()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 35, in __init__
    self.backend = database.get_backend(self.config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modoboa-installer/modoboa_installer/database.py", line 293, in get_backend
    return backend(config)
           ^^^^^^^^^^^^^^^
  File "/root/modoboa-installer/modoboa_installer/database.py", line 30, in __init__
    self.install_package()
  File "/root/modoboa-installer/modoboa_installer/database.py", line 191, in install_package
    super(MySQL, self).install_package()
  File "/root/modoboa-installer/modoboa_installer/database.py", line 34, in install_package
    package.backend.install_many(self.packages[package.backend.FORMAT])
  File "/root/modoboa-installer/modoboa_installer/package.py", line 65, in install_many
    return utils.exec_cmd("apt-get -o Dpkg::Progress-Fancy=0 install --quiet --assume-yes -o DPkg::options::=--force-confold {}".format(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 71, in exec_cmd
    for line in process.stdout:
KeyboardInterrupt

root@mail:~/modoboa-installer# 
`
I stopped as soon as i saw the permissions denied so it wouldn't complete the installation.
