### ISSUE TITLE
How can we Re-generate de SSL certificates automatically ?

### ISSUE THREAD

**Issue by fufales** [modoboa/modoboa-installer#293]
# Steps to reproduce
Wait for 3 months and the SSL certificate will not work anymore.

Then all clients with iPhone can't use their emails.

**Comment by tonioo** [comment]
@fufales The certificate should be updated automatically. This issue has been fixed a few months ago, when did you install Modoboa?

**Comment by fufales** [comment]
> @fufales The certificate should be updated automatically. This issue has been fixed a few months ago, when did you install Modoboa?

Thanks for replying tonioo, I've updated the instance a few months ago and still the same. 

Also, should we set all mails every 3 months with the certificate's update?
