### ISSUE TITLE
Ubuntu 20.04: No module named 'distro'

### ISSUE THREAD

**Issue by tsabi** [modoboa/modoboa-installer#340]
On a fresh ubuntu 20.04 install the run.py fails with missing module distro. You should install python3-distro first:
```apt install python3-distro```

# Impacted versions

* Distribution: Ubuntu
* Codename: Focal

# Steps to reproduce
fresh install, than run:
```
python3 run.py --stop-after-configfile-check domain.hu
```

# Full trace using --debug option or current behaviour
```
Traceback (most recent call last):
  File "/usr/src/modoboa-installer/modoboa_installer/utils.py", line 80, in dist_info
    import distro
ModuleNotFoundError: No module named 'distro'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from modoboa_installer import package
  File "/usr/src/modoboa-installer/modoboa_installer/package.py", line 105, in <module>
    backend = get_backend()
  File "/usr/src/modoboa-installer/modoboa_installer/package.py", line 93, in get_backend
    distname = utils.dist_name()
  File "/usr/src/modoboa-installer/modoboa_installer/utils.py", line 94, in dist_name
    name, version, _id = dist_info()
  File "/usr/src/modoboa-installer/modoboa_installer/utils.py", line 85, in dist_info
    return platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

# Expected behavior

**Comment by maxcco** [comment]
Hello 

On new install of ubuntu server 20.04 everything works as expected. I checked and python3-distro is present at install

What was the setting you use for ubuntu install ?

**Comment by tsabi** [comment]
I used an officially prepared LXC environment. I think they try to keep it as small as it could be.

**Comment by Paultje52** [comment]
I used `sudo apt-get install python3-distro`, and now everything works fine.

**Comment by almereyda** [comment]
I have `python3-distro` present in the `ubuntu:20.04` LXD image.

From the `ubuntu` remote `https://cloud-images.ubuntu.com/releases`

**Comment by tonioo** [comment]
this issue should be fixed now.

**Comment by ilovedogs1235** [comment]
still isn't fixed on current repos version (up to date as of 04/21/2023)
