### ISSUE TITLE
installer fails because of "new" pip dependency resolver

### ISSUE THREAD

**Issue by adestis-bm** [modoboa/modoboa-installer#388]
# Impacted versions

* Distribution: Ubuntu
* Codename: Focal (20.04.3)
* Arch: 64 Bits
* Database: PostgreSQL

Also tried with the following OSes, but stopped the installer after about 4~6 hours without any result:
- CentOS 7
- Debian 10
- Ubuntu 18.04 (latest version)

# Steps to reproduce

Basic Ubuntu 20.04.3 server setup (or any of the above listes OSes), with SSH enabled. After setup is completed (`XXXXX` is a real existing domain):

```shell
$ time sudo python3 run.py --debug XXXXX
[...]
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Downloading modoboa-webmail-1.1.4.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 3.0 MB/s
  Downloading modoboa-webmail-1.1.3.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 4.5 MB/s
  Downloading modoboa-webmail-1.1.2.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 4.3 MB/s
  Downloading modoboa-webmail-1.1.1.tar.gz (84 kB)
     |████████████████████████████████| 84 kB 3.8 MB/s
ERROR: Exception:
Traceback (most recent call last):
  File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 383, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/modoboa-admin.py", line 4, in <module>
    from modoboa.core.commands import handle_command_line
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa/core/__init__.py", line 3, in <module>
    from django.core.urlresolvers import reverse
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/urlresolvers.py", line 16, in <module>
    from django.http import Http404
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/http/__init__.py", line 4, in <module>
    from django.http.response import (
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/http/response.py", line 13, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/serializers/__init__.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/serializers/base.py", line 6, in <module>
    from django.db import models
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/__init__.py", line 6, in <module>
    from django.db.models.query import Q, QuerySet, Prefetch  # NOQA
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/query.py", line 13, in <module>
    from django.db.models.fields import AutoField, Empty, FieldDoesNotExist
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 18, in <module>
    from django import forms
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/forms/__init__.py", line 6, in <module>
    from django.forms.fields import *  # NOQA
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/forms/fields.py", line 18, in <module>
    from django.forms.utils import from_current_timezone, to_current_timezone
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/forms/utils.py", line 15, in <module>
    from django.utils.html import format_html, format_html_join, escape
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/utils/html.py", line 16, in <module>
    from .html_parser import HTMLParser, HTMLParseError
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/utils/html_parser.py", line 12, in <module>
    HTMLParseError = _html_parser.HTMLParseError
AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
None

real    1562m4.217s
user    1557m54.697s
sys     1m13.077s
```

Especially this line:

```shell
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
```

# Expected behavior

Installation finishes.

# Notes

- I did this installation on a Debian 10 about 5 months ago, and it finished pretty fast.
- Currently this does not work on any of the tested OS versions, because `pip` is installed in the modoboa environment at the latest version which uses the new dependency resolver.
- I tried setting `~modoboa/env/pip.conf` (aka `$VIRTUAL_ENV/pip.conf`) with different values, but currently I didn't find a working fix/hack to make the installer work. This idea was based on several "stackoverflow suggestions". Especially `use-deprecated=legacy-resolver` did not work, actually it fails pretty fast.

**Comment by solick** [comment]
Same problem here: I accidentally created a duplicated issue: https://github.com/modoboa/modoboa-installer/issues/390

3 weeks ago, a first test installation has run very fine and without error.

**Comment by Mik-Cryo** [comment]
Same problem. But I think I've a part of solution.
Create file /srv/modoboa/.pip/pip.conf and insert in pip.conf the 2 following lines
`[install]
use-deprecated = legacy-resolver`

**Comment by slayster** [comment]
Here with the same problem. Fresh installation on Debian 10 taking way longer than usual. I cancelled and tried again with --debug turned on. Noticed the error "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime." which led me to this thread. Tried the fix suggested by @Mik-Cryo above and also got exactly the same error "error in feedparser setup command: use_2to3 is invalid." I guess the legacy resolver is grabbing an incompatible version?

**Comment by Mik-Cryo** [comment]
Ok, just after https://github.com/modoboa/modoboa-installer/issues/388#issuecomment-919308439

```
$ wget https://files.pythonhosted.org/packages/ca/f4/91a056f11751701c24f86c692d92fee290b0ba3f99f657cdeb85ad3da402/feedparser-5.2.1.tar.gz
$ tar zxf feedparser-5.2.1.tar.gz
$ cd feedparser-5.2.1
$ nano setup.py
```
Comment the 2 following lines
```
if sys.version_info >= (3, ):
    extra['use_2to3'] = True
```
When it's done, repack and install
```
$ cd
$ tar zcf feedparser-5.2.1.tar.gz feedparser-5.2.1
$ ./env/bin/pip install feedparser-5.2.1.tar.gz
```
And... retry ./run.py

**Comment by Ranoiaetep** [comment]
@slayster @Mik-Cryo 
Seems like the problem related to `error in feedparser setup command: use_2to3 is invalid.`, is because the installing `feedparser` might or might not include a filed named `sgmllib.py`.

More can be found on the package page: https://pypi.org/project/feedparser/5.2.1/

I simply copied one from another `feedparser` package that was installed with `sgmllib.py` to `./env/lib/python3.8/site-packages`, and it seems to work.

**Comment by donholloway** [comment]
I'm relieved to see that I'm not the only one stuck in some type of resolver limbo.  Using the --debug let me see that it was endlessly downgrading.  I was about ready to go back to iredmail, but I like what I've read about better control over DKIM, etc.  Will try the legacy resolver fix.

**Comment by jarforce** [comment]
> @slayster @Mik-Cryo
> Seems like the problem related to `error in feedparser setup command: use_2to3 is invalid.`, is because the installing `feedparser` might or might not include a filed named `sgmllib.py`.
> 
> More can be found on the package page: https://pypi.org/project/feedparser/5.2.1/
> 
> I simply copied one from another `feedparser` package that was installed with `sgmllib.py` to `./env/lib/python3.8/site-packages`, and it seems to work.

error happened with 

> pip 21.2.4 (pip 21.2.4 from /srv/modoboa/env/lib/python3.8/site-packages/pip (python 3.8))

so revert to

> pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

everything working.

**Comment by chipincode** [comment]
Here are the steps I took to get it installed on Ubuntu 20.04:

Change to root:

`~$ sudo -i`

Download Modoboa Installer:

`~# git clone https://github.com/modoboa/modoboa-installer`

Install build dependencies: (The installer will keep crashing without: rustc, python3-feedparser & python3-lxml)

`~# apt install build-essential python3-dev python3-feedparser python3-lxml libxml2-dev libxslt-dev libjpeg-dev librrd-dev rrdtool libffi-dev libssl-dev rustc`

Installer will keep crashing if /tmp is noexec:

`~# mount -t tmpfs -o remount,exec tmpfs /tmp`

Run the Modoboa Installer to generate config file:

`~# cd modoboa-installer`
`~# ./run.py --stop-after-configfile-check <your domain>`

Edit config file:

`~# nano installer.cfg`

Change the following sections:

`   [certificate]`
`   type = letsencrypt`

`   [letsencrypt]`
`   email = <your email>@<your domain>`

`   [database]`
`   engine = <postgres or mysql>`

` ^S ^X`

Install Modoboa: (it's going to fail)

`~# ./run.py --interactive --debug  <your domain>`

Once you start seeing errors hit `^C`, then fix the issues keeping it from installing:

Install django-braces:

`~# su - modoboa`
`$ bash`
`~$ source ./env/bin/activate`
`~$ pip install django-braces`
`~$ exit`
`$ exit`

Copy feedparser & lxml to modoboa env:

`~# cp -r /usr/lib/python3/dist-packages/feedparser* /srv/modoboa/env/lib/python3.8/site-packages/`
`~# cp -r /usr/lib/python3/dist-packages/lxml* /srv/modoboa/env/lib/python3.8/site-packages/`

Re-install Modoboa:

`~# ./run.py --interactive --debug  <your domain>`

You should see: `Success!`

Remount /tmp noexec:

`~# mount -t tmpfs -o remount,noexec tmpfs /tmp`

Going to webmail site will generate server error, so let's fix it:

`~# nano /srv/modoboa/instance/instance/settings.py`

Change the following line:

` USE_TZ = false`

` ^S ^X`

Restart uWSGI:

`~# /etc/init.d/uwsgi restart`

Fix Postfix greylisting:

`~# nano /etc/postfix/main.cf`

Comment out the following:

`   postscreen_pipelining_enable = yes`
`   postscreen_pipelining_action = enforce`

`   postscreen_non_smtp_command_enable = yes`
`   postscreen_non_smtp_command_action = enforce`

`   postscreen_bare_newline_enable = yes`
`   postscreen_bare_newline_action = enforce`

` ^S ^X`

Restart Postfix:

`~# systemctl restart postfix`

`~# exit`

# Success!

**Comment by tonioo** [comment]
Just to let you know, I've pushed a fix for this issue. Problem is latest stable version of Modoboa (1.17) depends on old requirement versions which are not compatible with latest pip version anymore. If you update your installer copy, you can now use the --beta flag to install latest beta release instead, which has updated requirements.

**Comment by adestis-bm** [comment]
With the `--beta` option the installation finished:
<img width="640" alt="Bildschirmfoto 2021-09-22 um 12 02 37" src="https://user-images.githubusercontent.com/70651878/134324534-b8492825-d2f6-494c-8980-adb8c317abb8.png">

Two "things" cought my "attention" during that run. I just add the screenshot:

1) <img width="1033" alt="Bildschirmfoto 2021-09-22 um 11 53 33" src="https://user-images.githubusercontent.com/70651878/134324748-e9bdae8d-8928-4d34-985b-a8835b7919c1.png">

2) <img width="1161" alt="Bildschirmfoto 2021-09-22 um 11 55 38" src="https://user-images.githubusercontent.com/70651878/134324798-efef967d-f8af-4869-9a32-713f67f88811.png">

Thanks so far. I just hope the `--beta` won't be needed soon: it is somewhat "bitter" for our customer to have to use this switch for a "production" setup.

I will test the finished installation in the next hours to see if anything unsuspected shows up.

**Comment by tonioo** [comment]
@adestis-bm You should not see those messages anymore... Have you updated your installer local copy?

**Comment by adestis-bm** [comment]
Yes, I did. Well, if an `git pull` is sufficient?
Thank's to the "red" I saw them passing by. Next time I will capture the output.

**Comment by adestis-bm** [comment]
Sorry, clicked wrong button... distressed from colleagues at work... ;-)

**Comment by ukrolelo** [comment]
--beta fixes my endless loop on Debian 11  with:

0d18345a904cf3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-izopp0l9/rrdtool_2d995dc3e38b4554890d18345a904cf3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mus44m2s
         cwd: /tmp/pip-install-izopp0l9/rrdtool_2d995dc3e38b4554890d18345a904cf3/
    Complete output (5 lines):
    /tmp/tmp_python_rrdtooln5l82861/test_rrdtool.c:3:10: fatal error: rrdtoolmodule.h: No such file or directory
        3 | #include "rrdtoolmodule.h"
          |          ^~~~~~~~~~~~~~~~~
    compilation terminated.
    Error: Unable to compile the binary module. Do you have the rrdtool header and libraries installed?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8c/e5/9260566ccb617bdd2f954526daf6516e65dd663d72419c0cfae0284a311c/rrdtool-0.1.10.tar.gz#sha256=31a38964a7052d4a64edde487983540d142d866ba0b03a2bf7259d163951e477 (from https://pypi.org/simple/rrdtool/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading rrdtool-0.1.9.tar.gz (10 kB)

**Comment by tonioo** [comment]
@ukrolelo Do you have a more complete trace?

**Comment by ukrolelo** [comment]
It is fixed already, don't have logs anymore. the problem was that it can't install the rrdtool, the whole night loop. --beta fixed and GUI working :)

**Comment by tonioo** [comment]
Actually, I've just found the last issue here. I now force setuptools version to be < 58.0.0 (see https://setuptools.pypa.io/en/latest/history.html#v58-0-0).
So, it should not be necessary to use the --beta flag anymore unless you want to try to new web interface.

**Comment by solick** [comment]
@tonioo I updated can git pull but now the installer crashes at the ssl part:

    Generating new certificate using letsencrypt. 
    Traceback (most recent call last): 
      File "run.py", line 142, in <module>
        main(sys.argv[1:])
      File "run.py", line 123, in main
        ssl_backend.generate_cert() 
      File "/home/XXX/modoboa-installer/modoboa_installer/ssl.py", line 100, in generate_cert
        self.install_certbot() 
      File "/home/XXX/modoboa-installer/modoboa_installer/ssl.py", line 77, in install_certbot
        name, version, _id = utils.dist_info()
    ValueError: not enough values to unpack (expected 3, got 2)`

Its ubuntu 20.04.3

**Comment by tonioo** [comment]
@solick I've pushed a fix for that

**Comment by solick** [comment]
@tonioo thanks. Running the installer again still throws a lot of errors. I had to kill the vm and start from scratch but than it run fine without error.

It would be great to habe a backup / restore script to have a usable solution for a fresh install and restore of the data if something similar will happen during upgrade.
